Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped100_tsim100.tsv ../sims/svgs/test/qq_tcompared_tmapped100_tsim100.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped100_tsim100.tsv ../sims/svgs/test/roc_tcompared_tmapped100_tsim100.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped110_tsim110.tsv ../sims/svgs/test/qq_tcompared_tmapped110_tsim110.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped110_tsim110.tsv ../sims/svgs/test/roc_tcompared_tmapped110_tsim110.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped120_tsim120.tsv ../sims/svgs/test/qq_tcompared_tmapped120_tsim120.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped120_tsim120.tsv ../sims/svgs/test/roc_tcompared_tmapped120_tsim120.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped130_tsim130.tsv ../sims/svgs/test/qq_tcompared_tmapped130_tsim130.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped130_tsim130.tsv ../sims/svgs/test/roc_tcompared_tmapped130_tsim130.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped140_tsim140.tsv ../sims/svgs/test/qq_tcompared_tmapped140_tsim140.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped140_tsim140.tsv ../sims/svgs/test/roc_tcompared_tmapped140_tsim140.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped150_tsim150.tsv ../sims/svgs/test/qq_tcompared_tmapped150_tsim150.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped150_tsim150.tsv ../sims/svgs/test/roc_tcompared_tmapped150_tsim150.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped160_tsim160.tsv ../sims/svgs/test/qq_tcompared_tmapped160_tsim160.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped160_tsim160.tsv ../sims/svgs/test/roc_tcompared_tmapped160_tsim160.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped170_tsim170.tsv ../sims/svgs/test/qq_tcompared_tmapped170_tsim170.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped170_tsim170.tsv ../sims/svgs/test/roc_tcompared_tmapped170_tsim170.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped180_tsim180.tsv ../sims/svgs/test/qq_tcompared_tmapped180_tsim180.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped180_tsim180.tsv ../sims/svgs/test/roc_tcompared_tmapped180_tsim180.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped190_tsim190.tsv ../sims/svgs/test/qq_tcompared_tmapped190_tsim190.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped190_tsim190.tsv ../sims/svgs/test/roc_tcompared_tmapped190_tsim190.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped200_tsim200.tsv ../sims/svgs/test/qq_tcompared_tmapped200_tsim200.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped200_tsim200.tsv ../sims/svgs/test/roc_tcompared_tmapped200_tsim200.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped210_tsim210.tsv ../sims/svgs/test/qq_tcompared_tmapped210_tsim210.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped210_tsim210.tsv ../sims/svgs/test/roc_tcompared_tmapped210_tsim210.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped220_tsim220.tsv ../sims/svgs/test/qq_tcompared_tmapped220_tsim220.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped220_tsim220.tsv ../sims/svgs/test/roc_tcompared_tmapped220_tsim220.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped230_tsim230.tsv ../sims/svgs/test/qq_tcompared_tmapped230_tsim230.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped230_tsim230.tsv ../sims/svgs/test/roc_tcompared_tmapped230_tsim230.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped240_tsim240.tsv ../sims/svgs/test/qq_tcompared_tmapped240_tsim240.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped240_tsim240.tsv ../sims/svgs/test/roc_tcompared_tmapped240_tsim240.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped250_tsim250.tsv ../sims/svgs/test/qq_tcompared_tmapped250_tsim250.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped250_tsim250.tsv ../sims/svgs/test/roc_tcompared_tmapped250_tsim250.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped70_tsim70.tsv ../sims/svgs/test/qq_tcompared_tmapped70_tsim70.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped70_tsim70.tsv ../sims/svgs/test/roc_tcompared_tmapped70_tsim70.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped80_tsim80.tsv ../sims/svgs/test/qq_tcompared_tmapped80_tsim80.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped80_tsim80.tsv ../sims/svgs/test/roc_tcompared_tmapped80_tsim80.svg
Rscript ~/vg/scripts/plot-qq.R tcompared_tmapped90_tsim90.tsv ../sims/svgs/test/qq_tcompared_tmapped90_tsim90.svg
Rscript ~/vg/scripts/plot-roc.R tcompared_tmapped90_tsim90.tsv ../sims/svgs/test/roc_tcompared_tmapped90_tsim90.svg
