Rscript ~/vg/scripts/plot-qq.R stats_b_100.tsv stats_b_100.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_110.tsv stats_b_110.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_120.tsv stats_b_120.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_130.tsv stats_b_130.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_140.tsv stats_b_140.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_150.tsv stats_b_150.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_160.tsv stats_b_160.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_170.tsv stats_b_170.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_180.tsv stats_b_180.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_190.tsv stats_b_190.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_200.tsv stats_b_200.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_210.tsv stats_b_210.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_220.tsv stats_b_220.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_230.tsv stats_b_230.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_240.tsv stats_b_240.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_250.tsv stats_b_250.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_70.tsv stats_b_70.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_80.tsv stats_b_80.svg
Rscript ~/vg/scripts/plot-qq.R stats_b_90.tsv stats_b_90.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_100.tsv stats_bm_100.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_110.tsv stats_bm_110.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_120.tsv stats_bm_120.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_130.tsv stats_bm_130.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_140.tsv stats_bm_140.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_150.tsv stats_bm_150.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_160.tsv stats_bm_160.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_170.tsv stats_bm_170.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_180.tsv stats_bm_180.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_190.tsv stats_bm_190.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_200.tsv stats_bm_200.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_210.tsv stats_bm_210.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_220.tsv stats_bm_220.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_230.tsv stats_bm_230.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_240.tsv stats_bm_240.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_250.tsv stats_bm_250.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_70.tsv stats_bm_70.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_80.tsv stats_bm_80.svg
Rscript ~/vg/scripts/plot-qq.R stats_bm_90.tsv stats_bm_90.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_100.tsv stats_m_100.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_110.tsv stats_m_110.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_120.tsv stats_m_120.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_130.tsv stats_m_130.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_140.tsv stats_m_140.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_150.tsv stats_m_150.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_160.tsv stats_m_160.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_170.tsv stats_m_170.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_180.tsv stats_m_180.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_190.tsv stats_m_190.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_200.tsv stats_m_200.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_210.tsv stats_m_210.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_220.tsv stats_m_220.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_230.tsv stats_m_230.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_240.tsv stats_m_240.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_250.tsv stats_m_250.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_70.tsv stats_m_70.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_80.tsv stats_m_80.svg
Rscript ~/vg/scripts/plot-qq.R stats_m_90.tsv stats_m_90.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_100.tsv stats_ms_100.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_110.tsv stats_ms_110.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_120.tsv stats_ms_120.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_130.tsv stats_ms_130.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_140.tsv stats_ms_140.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_150.tsv stats_ms_150.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_160.tsv stats_ms_160.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_170.tsv stats_ms_170.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_180.tsv stats_ms_180.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_190.tsv stats_ms_190.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_200.tsv stats_ms_200.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_210.tsv stats_ms_210.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_220.tsv stats_ms_220.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_230.tsv stats_ms_230.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_240.tsv stats_ms_240.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_250.tsv stats_ms_250.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_70.tsv stats_ms_70.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_80.tsv stats_ms_80.svg
Rscript ~/vg/scripts/plot-qq.R stats_ms_90.tsv stats_ms_90.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_100.tsv stats_r_100.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_110.tsv stats_r_110.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_120.tsv stats_r_120.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_130.tsv stats_r_130.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_140.tsv stats_r_140.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_150.tsv stats_r_150.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_160.tsv stats_r_160.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_170.tsv stats_r_170.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_180.tsv stats_r_180.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_190.tsv stats_r_190.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_200.tsv stats_r_200.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_210.tsv stats_r_210.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_220.tsv stats_r_220.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_230.tsv stats_r_230.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_240.tsv stats_r_240.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_250.tsv stats_r_250.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_70.tsv stats_r_70.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_80.tsv stats_r_80.svg
Rscript ~/vg/scripts/plot-qq.R stats_r_90.tsv stats_r_90.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_100.tsv tstats_b_100.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_110.tsv tstats_b_110.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_120.tsv tstats_b_120.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_130.tsv tstats_b_130.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_140.tsv tstats_b_140.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_150.tsv tstats_b_150.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_160.tsv tstats_b_160.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_170.tsv tstats_b_170.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_180.tsv tstats_b_180.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_190.tsv tstats_b_190.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_200.tsv tstats_b_200.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_210.tsv tstats_b_210.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_220.tsv tstats_b_220.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_230.tsv tstats_b_230.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_240.tsv tstats_b_240.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_250.tsv tstats_b_250.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_70.tsv tstats_b_70.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_80.tsv tstats_b_80.svg
Rscript ~/vg/scripts/plot-qq.R tstats_b_90.tsv tstats_b_90.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_100.tsv tstats_bm_100.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_110.tsv tstats_bm_110.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_120.tsv tstats_bm_120.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_130.tsv tstats_bm_130.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_140.tsv tstats_bm_140.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_150.tsv tstats_bm_150.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_160.tsv tstats_bm_160.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_170.tsv tstats_bm_170.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_180.tsv tstats_bm_180.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_190.tsv tstats_bm_190.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_200.tsv tstats_bm_200.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_210.tsv tstats_bm_210.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_220.tsv tstats_bm_220.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_230.tsv tstats_bm_230.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_240.tsv tstats_bm_240.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_250.tsv tstats_bm_250.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_70.tsv tstats_bm_70.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_80.tsv tstats_bm_80.svg
Rscript ~/vg/scripts/plot-qq.R tstats_bm_90.tsv tstats_bm_90.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_100.tsv tstats_m_100.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_110.tsv tstats_m_110.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_120.tsv tstats_m_120.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_130.tsv tstats_m_130.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_140.tsv tstats_m_140.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_150.tsv tstats_m_150.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_160.tsv tstats_m_160.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_170.tsv tstats_m_170.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_180.tsv tstats_m_180.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_190.tsv tstats_m_190.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_200.tsv tstats_m_200.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_210.tsv tstats_m_210.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_220.tsv tstats_m_220.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_230.tsv tstats_m_230.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_240.tsv tstats_m_240.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_250.tsv tstats_m_250.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_70.tsv tstats_m_70.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_80.tsv tstats_m_80.svg
Rscript ~/vg/scripts/plot-qq.R tstats_m_90.tsv tstats_m_90.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_100.tsv tstats_ms_100.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_110.tsv tstats_ms_110.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_120.tsv tstats_ms_120.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_130.tsv tstats_ms_130.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_140.tsv tstats_ms_140.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_150.tsv tstats_ms_150.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_160.tsv tstats_ms_160.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_170.tsv tstats_ms_170.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_180.tsv tstats_ms_180.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_190.tsv tstats_ms_190.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_200.tsv tstats_ms_200.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_210.tsv tstats_ms_210.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_220.tsv tstats_ms_220.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_230.tsv tstats_ms_230.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_240.tsv tstats_ms_240.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_250.tsv tstats_ms_250.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_70.tsv tstats_ms_70.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_80.tsv tstats_ms_80.svg
Rscript ~/vg/scripts/plot-qq.R tstats_ms_90.tsv tstats_ms_90.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_100.tsv tstats_r_100.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_110.tsv tstats_r_110.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_120.tsv tstats_r_120.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_130.tsv tstats_r_130.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_140.tsv tstats_r_140.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_150.tsv tstats_r_150.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_160.tsv tstats_r_160.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_170.tsv tstats_r_170.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_180.tsv tstats_r_180.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_190.tsv tstats_r_190.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_200.tsv tstats_r_200.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_210.tsv tstats_r_210.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_220.tsv tstats_r_220.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_230.tsv tstats_r_230.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_240.tsv tstats_r_240.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_250.tsv tstats_r_250.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_70.tsv tstats_r_70.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_80.tsv tstats_r_80.svg
Rscript ~/vg/scripts/plot-qq.R tstats_r_90.tsv tstats_r_90.svg
