Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped100_tsim100.tsv sims/svgs/test/qq_tcompared_tmapped100_tsim100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped100_tsim100.tsv sims/svgs/test/roc_tcompared_tmapped100_tsim100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped110_tsim110.tsv sims/svgs/test/qq_tcompared_tmapped110_tsim110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped110_tsim110.tsv sims/svgs/test/roc_tcompared_tmapped110_tsim110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped120_tsim120.tsv sims/svgs/test/qq_tcompared_tmapped120_tsim120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped120_tsim120.tsv sims/svgs/test/roc_tcompared_tmapped120_tsim120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped130_tsim130.tsv sims/svgs/test/qq_tcompared_tmapped130_tsim130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped130_tsim130.tsv sims/svgs/test/roc_tcompared_tmapped130_tsim130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped140_tsim140.tsv sims/svgs/test/qq_tcompared_tmapped140_tsim140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped140_tsim140.tsv sims/svgs/test/roc_tcompared_tmapped140_tsim140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped150_tsim150.tsv sims/svgs/test/qq_tcompared_tmapped150_tsim150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped150_tsim150.tsv sims/svgs/test/roc_tcompared_tmapped150_tsim150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped160_tsim160.tsv sims/svgs/test/qq_tcompared_tmapped160_tsim160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped160_tsim160.tsv sims/svgs/test/roc_tcompared_tmapped160_tsim160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped170_tsim170.tsv sims/svgs/test/qq_tcompared_tmapped170_tsim170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped170_tsim170.tsv sims/svgs/test/roc_tcompared_tmapped170_tsim170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped180_tsim180.tsv sims/svgs/test/qq_tcompared_tmapped180_tsim180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped180_tsim180.tsv sims/svgs/test/roc_tcompared_tmapped180_tsim180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped190_tsim190.tsv sims/svgs/test/qq_tcompared_tmapped190_tsim190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped190_tsim190.tsv sims/svgs/test/roc_tcompared_tmapped190_tsim190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped200_tsim200.tsv sims/svgs/test/qq_tcompared_tmapped200_tsim200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped200_tsim200.tsv sims/svgs/test/roc_tcompared_tmapped200_tsim200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped210_tsim210.tsv sims/svgs/test/qq_tcompared_tmapped210_tsim210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped210_tsim210.tsv sims/svgs/test/roc_tcompared_tmapped210_tsim210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped220_tsim220.tsv sims/svgs/test/qq_tcompared_tmapped220_tsim220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped220_tsim220.tsv sims/svgs/test/roc_tcompared_tmapped220_tsim220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped230_tsim230.tsv sims/svgs/test/qq_tcompared_tmapped230_tsim230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped230_tsim230.tsv sims/svgs/test/roc_tcompared_tmapped230_tsim230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped240_tsim240.tsv sims/svgs/test/qq_tcompared_tmapped240_tsim240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped240_tsim240.tsv sims/svgs/test/roc_tcompared_tmapped240_tsim240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped250_tsim250.tsv sims/svgs/test/qq_tcompared_tmapped250_tsim250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped250_tsim250.tsv sims/svgs/test/roc_tcompared_tmapped250_tsim250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped70_tsim70.tsv sims/svgs/test/qq_tcompared_tmapped70_tsim70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped70_tsim70.tsv sims/svgs/test/roc_tcompared_tmapped70_tsim70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped80_tsim80.tsv sims/svgs/test/qq_tcompared_tmapped80_tsim80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped80_tsim80.tsv sims/svgs/test/roc_tcompared_tmapped80_tsim80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tcompared_tmapped90_tsim90.tsv sims/svgs/test/qq_tcompared_tmapped90_tsim90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tcompared_tmapped90_tsim90.tsv sims/svgs/test/roc_tcompared_tmapped90_tsim90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_100.tsv sims/svgs/test/qq_tstats_b_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_100.tsv sims/svgs/test/roc_tstats_b_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_110.tsv sims/svgs/test/qq_tstats_b_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_110.tsv sims/svgs/test/roc_tstats_b_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_120.tsv sims/svgs/test/qq_tstats_b_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_120.tsv sims/svgs/test/roc_tstats_b_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_130.tsv sims/svgs/test/qq_tstats_b_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_130.tsv sims/svgs/test/roc_tstats_b_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_140.tsv sims/svgs/test/qq_tstats_b_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_140.tsv sims/svgs/test/roc_tstats_b_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_150.tsv sims/svgs/test/qq_tstats_b_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_150.tsv sims/svgs/test/roc_tstats_b_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_160.tsv sims/svgs/test/qq_tstats_b_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_160.tsv sims/svgs/test/roc_tstats_b_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_170.tsv sims/svgs/test/qq_tstats_b_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_170.tsv sims/svgs/test/roc_tstats_b_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_180.tsv sims/svgs/test/qq_tstats_b_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_180.tsv sims/svgs/test/roc_tstats_b_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_190.tsv sims/svgs/test/qq_tstats_b_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_190.tsv sims/svgs/test/roc_tstats_b_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_200.tsv sims/svgs/test/qq_tstats_b_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_200.tsv sims/svgs/test/roc_tstats_b_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_210.tsv sims/svgs/test/qq_tstats_b_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_210.tsv sims/svgs/test/roc_tstats_b_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_220.tsv sims/svgs/test/qq_tstats_b_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_220.tsv sims/svgs/test/roc_tstats_b_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_230.tsv sims/svgs/test/qq_tstats_b_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_230.tsv sims/svgs/test/roc_tstats_b_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_240.tsv sims/svgs/test/qq_tstats_b_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_240.tsv sims/svgs/test/roc_tstats_b_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_250.tsv sims/svgs/test/qq_tstats_b_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_250.tsv sims/svgs/test/roc_tstats_b_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_70.tsv sims/svgs/test/qq_tstats_b_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_70.tsv sims/svgs/test/roc_tstats_b_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_80.tsv sims/svgs/test/qq_tstats_b_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_80.tsv sims/svgs/test/roc_tstats_b_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_b_90.tsv sims/svgs/test/qq_tstats_b_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_b_90.tsv sims/svgs/test/roc_tstats_b_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_100.tsv sims/svgs/test/qq_tstats_bm_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_100.tsv sims/svgs/test/roc_tstats_bm_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_110.tsv sims/svgs/test/qq_tstats_bm_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_110.tsv sims/svgs/test/roc_tstats_bm_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_120.tsv sims/svgs/test/qq_tstats_bm_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_120.tsv sims/svgs/test/roc_tstats_bm_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_130.tsv sims/svgs/test/qq_tstats_bm_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_130.tsv sims/svgs/test/roc_tstats_bm_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_140.tsv sims/svgs/test/qq_tstats_bm_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_140.tsv sims/svgs/test/roc_tstats_bm_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_150.tsv sims/svgs/test/qq_tstats_bm_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_150.tsv sims/svgs/test/roc_tstats_bm_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_160.tsv sims/svgs/test/qq_tstats_bm_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_160.tsv sims/svgs/test/roc_tstats_bm_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_170.tsv sims/svgs/test/qq_tstats_bm_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_170.tsv sims/svgs/test/roc_tstats_bm_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_180.tsv sims/svgs/test/qq_tstats_bm_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_180.tsv sims/svgs/test/roc_tstats_bm_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_190.tsv sims/svgs/test/qq_tstats_bm_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_190.tsv sims/svgs/test/roc_tstats_bm_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_200.tsv sims/svgs/test/qq_tstats_bm_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_200.tsv sims/svgs/test/roc_tstats_bm_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_210.tsv sims/svgs/test/qq_tstats_bm_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_210.tsv sims/svgs/test/roc_tstats_bm_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_220.tsv sims/svgs/test/qq_tstats_bm_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_220.tsv sims/svgs/test/roc_tstats_bm_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_230.tsv sims/svgs/test/qq_tstats_bm_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_230.tsv sims/svgs/test/roc_tstats_bm_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_240.tsv sims/svgs/test/qq_tstats_bm_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_240.tsv sims/svgs/test/roc_tstats_bm_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_250.tsv sims/svgs/test/qq_tstats_bm_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_250.tsv sims/svgs/test/roc_tstats_bm_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_70.tsv sims/svgs/test/qq_tstats_bm_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_70.tsv sims/svgs/test/roc_tstats_bm_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_80.tsv sims/svgs/test/qq_tstats_bm_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_80.tsv sims/svgs/test/roc_tstats_bm_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_bm_90.tsv sims/svgs/test/qq_tstats_bm_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_bm_90.tsv sims/svgs/test/roc_tstats_bm_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_100.tsv sims/svgs/test/qq_tstats_m_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_100.tsv sims/svgs/test/roc_tstats_m_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_110.tsv sims/svgs/test/qq_tstats_m_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_110.tsv sims/svgs/test/roc_tstats_m_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_120.tsv sims/svgs/test/qq_tstats_m_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_120.tsv sims/svgs/test/roc_tstats_m_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_130.tsv sims/svgs/test/qq_tstats_m_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_130.tsv sims/svgs/test/roc_tstats_m_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_140.tsv sims/svgs/test/qq_tstats_m_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_140.tsv sims/svgs/test/roc_tstats_m_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_150.tsv sims/svgs/test/qq_tstats_m_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_150.tsv sims/svgs/test/roc_tstats_m_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_160.tsv sims/svgs/test/qq_tstats_m_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_160.tsv sims/svgs/test/roc_tstats_m_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_170.tsv sims/svgs/test/qq_tstats_m_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_170.tsv sims/svgs/test/roc_tstats_m_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_180.tsv sims/svgs/test/qq_tstats_m_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_180.tsv sims/svgs/test/roc_tstats_m_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_190.tsv sims/svgs/test/qq_tstats_m_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_190.tsv sims/svgs/test/roc_tstats_m_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_200.tsv sims/svgs/test/qq_tstats_m_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_200.tsv sims/svgs/test/roc_tstats_m_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_210.tsv sims/svgs/test/qq_tstats_m_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_210.tsv sims/svgs/test/roc_tstats_m_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_220.tsv sims/svgs/test/qq_tstats_m_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_220.tsv sims/svgs/test/roc_tstats_m_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_230.tsv sims/svgs/test/qq_tstats_m_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_230.tsv sims/svgs/test/roc_tstats_m_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_240.tsv sims/svgs/test/qq_tstats_m_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_240.tsv sims/svgs/test/roc_tstats_m_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_250.tsv sims/svgs/test/qq_tstats_m_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_250.tsv sims/svgs/test/roc_tstats_m_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_70.tsv sims/svgs/test/qq_tstats_m_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_70.tsv sims/svgs/test/roc_tstats_m_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_80.tsv sims/svgs/test/qq_tstats_m_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_80.tsv sims/svgs/test/roc_tstats_m_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_m_90.tsv sims/svgs/test/qq_tstats_m_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_m_90.tsv sims/svgs/test/roc_tstats_m_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_100.tsv sims/svgs/test/qq_tstats_ms_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_100.tsv sims/svgs/test/roc_tstats_ms_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_110.tsv sims/svgs/test/qq_tstats_ms_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_110.tsv sims/svgs/test/roc_tstats_ms_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_120.tsv sims/svgs/test/qq_tstats_ms_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_120.tsv sims/svgs/test/roc_tstats_ms_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_130.tsv sims/svgs/test/qq_tstats_ms_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_130.tsv sims/svgs/test/roc_tstats_ms_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_140.tsv sims/svgs/test/qq_tstats_ms_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_140.tsv sims/svgs/test/roc_tstats_ms_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_150.tsv sims/svgs/test/qq_tstats_ms_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_150.tsv sims/svgs/test/roc_tstats_ms_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_160.tsv sims/svgs/test/qq_tstats_ms_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_160.tsv sims/svgs/test/roc_tstats_ms_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_170.tsv sims/svgs/test/qq_tstats_ms_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_170.tsv sims/svgs/test/roc_tstats_ms_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_180.tsv sims/svgs/test/qq_tstats_ms_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_180.tsv sims/svgs/test/roc_tstats_ms_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_190.tsv sims/svgs/test/qq_tstats_ms_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_190.tsv sims/svgs/test/roc_tstats_ms_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_200.tsv sims/svgs/test/qq_tstats_ms_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_200.tsv sims/svgs/test/roc_tstats_ms_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_210.tsv sims/svgs/test/qq_tstats_ms_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_210.tsv sims/svgs/test/roc_tstats_ms_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_220.tsv sims/svgs/test/qq_tstats_ms_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_220.tsv sims/svgs/test/roc_tstats_ms_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_230.tsv sims/svgs/test/qq_tstats_ms_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_230.tsv sims/svgs/test/roc_tstats_ms_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_240.tsv sims/svgs/test/qq_tstats_ms_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_240.tsv sims/svgs/test/roc_tstats_ms_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_250.tsv sims/svgs/test/qq_tstats_ms_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_250.tsv sims/svgs/test/roc_tstats_ms_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_70.tsv sims/svgs/test/qq_tstats_ms_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_70.tsv sims/svgs/test/roc_tstats_ms_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_80.tsv sims/svgs/test/qq_tstats_ms_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_80.tsv sims/svgs/test/roc_tstats_ms_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_ms_90.tsv sims/svgs/test/qq_tstats_ms_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_ms_90.tsv sims/svgs/test/roc_tstats_ms_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_100.tsv sims/svgs/test/qq_tstats_r_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_100.tsv sims/svgs/test/roc_tstats_r_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_110.tsv sims/svgs/test/qq_tstats_r_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_110.tsv sims/svgs/test/roc_tstats_r_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_120.tsv sims/svgs/test/qq_tstats_r_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_120.tsv sims/svgs/test/roc_tstats_r_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_130.tsv sims/svgs/test/qq_tstats_r_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_130.tsv sims/svgs/test/roc_tstats_r_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_140.tsv sims/svgs/test/qq_tstats_r_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_140.tsv sims/svgs/test/roc_tstats_r_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_150.tsv sims/svgs/test/qq_tstats_r_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_150.tsv sims/svgs/test/roc_tstats_r_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_160.tsv sims/svgs/test/qq_tstats_r_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_160.tsv sims/svgs/test/roc_tstats_r_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_170.tsv sims/svgs/test/qq_tstats_r_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_170.tsv sims/svgs/test/roc_tstats_r_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_180.tsv sims/svgs/test/qq_tstats_r_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_180.tsv sims/svgs/test/roc_tstats_r_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_190.tsv sims/svgs/test/qq_tstats_r_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_190.tsv sims/svgs/test/roc_tstats_r_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_200.tsv sims/svgs/test/qq_tstats_r_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_200.tsv sims/svgs/test/roc_tstats_r_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_210.tsv sims/svgs/test/qq_tstats_r_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_210.tsv sims/svgs/test/roc_tstats_r_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_220.tsv sims/svgs/test/qq_tstats_r_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_220.tsv sims/svgs/test/roc_tstats_r_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_230.tsv sims/svgs/test/qq_tstats_r_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_230.tsv sims/svgs/test/roc_tstats_r_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_240.tsv sims/svgs/test/qq_tstats_r_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_240.tsv sims/svgs/test/roc_tstats_r_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_250.tsv sims/svgs/test/qq_tstats_r_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_250.tsv sims/svgs/test/roc_tstats_r_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_70.tsv sims/svgs/test/qq_tstats_r_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_70.tsv sims/svgs/test/roc_tstats_r_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_80.tsv sims/svgs/test/qq_tstats_r_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_80.tsv sims/svgs/test/roc_tstats_r_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/test/tstats_r_90.tsv sims/svgs/test/qq_tstats_r_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/test/tstats_r_90.tsv sims/svgs/test/roc_tstats_r_90.svg
