Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped100_sim100.tsv sims/svgs/train/qq_compared_mapped100_sim100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped100_sim100.tsv sims/svgs/train/roc_compared_mapped100_sim100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped110_sim110.tsv sims/svgs/train/qq_compared_mapped110_sim110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped110_sim110.tsv sims/svgs/train/roc_compared_mapped110_sim110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped120_sim120.tsv sims/svgs/train/qq_compared_mapped120_sim120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped120_sim120.tsv sims/svgs/train/roc_compared_mapped120_sim120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped130_sim130.tsv sims/svgs/train/qq_compared_mapped130_sim130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped130_sim130.tsv sims/svgs/train/roc_compared_mapped130_sim130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped140_sim140.tsv sims/svgs/train/qq_compared_mapped140_sim140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped140_sim140.tsv sims/svgs/train/roc_compared_mapped140_sim140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped150_sim150.tsv sims/svgs/train/qq_compared_mapped150_sim150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped150_sim150.tsv sims/svgs/train/roc_compared_mapped150_sim150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped160_sim160.tsv sims/svgs/train/qq_compared_mapped160_sim160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped160_sim160.tsv sims/svgs/train/roc_compared_mapped160_sim160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped170_sim170.tsv sims/svgs/train/qq_compared_mapped170_sim170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped170_sim170.tsv sims/svgs/train/roc_compared_mapped170_sim170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped180_sim180.tsv sims/svgs/train/qq_compared_mapped180_sim180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped180_sim180.tsv sims/svgs/train/roc_compared_mapped180_sim180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped190_sim190.tsv sims/svgs/train/qq_compared_mapped190_sim190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped190_sim190.tsv sims/svgs/train/roc_compared_mapped190_sim190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped200_sim200.tsv sims/svgs/train/qq_compared_mapped200_sim200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped200_sim200.tsv sims/svgs/train/roc_compared_mapped200_sim200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped210_sim210.tsv sims/svgs/train/qq_compared_mapped210_sim210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped210_sim210.tsv sims/svgs/train/roc_compared_mapped210_sim210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped220_sim220.tsv sims/svgs/train/qq_compared_mapped220_sim220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped220_sim220.tsv sims/svgs/train/roc_compared_mapped220_sim220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped230_sim230.tsv sims/svgs/train/qq_compared_mapped230_sim230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped230_sim230.tsv sims/svgs/train/roc_compared_mapped230_sim230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped240_sim240.tsv sims/svgs/train/qq_compared_mapped240_sim240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped240_sim240.tsv sims/svgs/train/roc_compared_mapped240_sim240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped250_sim250.tsv sims/svgs/train/qq_compared_mapped250_sim250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped250_sim250.tsv sims/svgs/train/roc_compared_mapped250_sim250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped70_sim70.tsv sims/svgs/train/qq_compared_mapped70_sim70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped70_sim70.tsv sims/svgs/train/roc_compared_mapped70_sim70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped80_sim80.tsv sims/svgs/train/qq_compared_mapped80_sim80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped80_sim80.tsv sims/svgs/train/roc_compared_mapped80_sim80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/compared_mapped90_sim90.tsv sims/svgs/train/qq_compared_mapped90_sim90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/compared_mapped90_sim90.tsv sims/svgs/train/roc_compared_mapped90_sim90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_100.tsv sims/svgs/train/qq_stats_b_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_100.tsv sims/svgs/train/roc_stats_b_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_110.tsv sims/svgs/train/qq_stats_b_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_110.tsv sims/svgs/train/roc_stats_b_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_120.tsv sims/svgs/train/qq_stats_b_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_120.tsv sims/svgs/train/roc_stats_b_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_130.tsv sims/svgs/train/qq_stats_b_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_130.tsv sims/svgs/train/roc_stats_b_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_140.tsv sims/svgs/train/qq_stats_b_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_140.tsv sims/svgs/train/roc_stats_b_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_150.tsv sims/svgs/train/qq_stats_b_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_150.tsv sims/svgs/train/roc_stats_b_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_160.tsv sims/svgs/train/qq_stats_b_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_160.tsv sims/svgs/train/roc_stats_b_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_170.tsv sims/svgs/train/qq_stats_b_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_170.tsv sims/svgs/train/roc_stats_b_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_180.tsv sims/svgs/train/qq_stats_b_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_180.tsv sims/svgs/train/roc_stats_b_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_190.tsv sims/svgs/train/qq_stats_b_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_190.tsv sims/svgs/train/roc_stats_b_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_200.tsv sims/svgs/train/qq_stats_b_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_200.tsv sims/svgs/train/roc_stats_b_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_210.tsv sims/svgs/train/qq_stats_b_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_210.tsv sims/svgs/train/roc_stats_b_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_220.tsv sims/svgs/train/qq_stats_b_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_220.tsv sims/svgs/train/roc_stats_b_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_230.tsv sims/svgs/train/qq_stats_b_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_230.tsv sims/svgs/train/roc_stats_b_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_240.tsv sims/svgs/train/qq_stats_b_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_240.tsv sims/svgs/train/roc_stats_b_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_250.tsv sims/svgs/train/qq_stats_b_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_250.tsv sims/svgs/train/roc_stats_b_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_70.tsv sims/svgs/train/qq_stats_b_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_70.tsv sims/svgs/train/roc_stats_b_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_80.tsv sims/svgs/train/qq_stats_b_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_80.tsv sims/svgs/train/roc_stats_b_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_b_90.tsv sims/svgs/train/qq_stats_b_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_b_90.tsv sims/svgs/train/roc_stats_b_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_100.tsv sims/svgs/train/qq_stats_bm_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_100.tsv sims/svgs/train/roc_stats_bm_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_110.tsv sims/svgs/train/qq_stats_bm_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_110.tsv sims/svgs/train/roc_stats_bm_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_120.tsv sims/svgs/train/qq_stats_bm_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_120.tsv sims/svgs/train/roc_stats_bm_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_130.tsv sims/svgs/train/qq_stats_bm_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_130.tsv sims/svgs/train/roc_stats_bm_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_140.tsv sims/svgs/train/qq_stats_bm_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_140.tsv sims/svgs/train/roc_stats_bm_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_150.tsv sims/svgs/train/qq_stats_bm_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_150.tsv sims/svgs/train/roc_stats_bm_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_160.tsv sims/svgs/train/qq_stats_bm_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_160.tsv sims/svgs/train/roc_stats_bm_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_170.tsv sims/svgs/train/qq_stats_bm_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_170.tsv sims/svgs/train/roc_stats_bm_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_180.tsv sims/svgs/train/qq_stats_bm_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_180.tsv sims/svgs/train/roc_stats_bm_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_190.tsv sims/svgs/train/qq_stats_bm_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_190.tsv sims/svgs/train/roc_stats_bm_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_200.tsv sims/svgs/train/qq_stats_bm_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_200.tsv sims/svgs/train/roc_stats_bm_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_210.tsv sims/svgs/train/qq_stats_bm_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_210.tsv sims/svgs/train/roc_stats_bm_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_220.tsv sims/svgs/train/qq_stats_bm_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_220.tsv sims/svgs/train/roc_stats_bm_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_230.tsv sims/svgs/train/qq_stats_bm_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_230.tsv sims/svgs/train/roc_stats_bm_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_240.tsv sims/svgs/train/qq_stats_bm_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_240.tsv sims/svgs/train/roc_stats_bm_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_250.tsv sims/svgs/train/qq_stats_bm_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_250.tsv sims/svgs/train/roc_stats_bm_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_70.tsv sims/svgs/train/qq_stats_bm_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_70.tsv sims/svgs/train/roc_stats_bm_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_80.tsv sims/svgs/train/qq_stats_bm_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_80.tsv sims/svgs/train/roc_stats_bm_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_bm_90.tsv sims/svgs/train/qq_stats_bm_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_bm_90.tsv sims/svgs/train/roc_stats_bm_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_100.tsv sims/svgs/train/qq_stats_m_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_100.tsv sims/svgs/train/roc_stats_m_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_110.tsv sims/svgs/train/qq_stats_m_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_110.tsv sims/svgs/train/roc_stats_m_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_120.tsv sims/svgs/train/qq_stats_m_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_120.tsv sims/svgs/train/roc_stats_m_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_130.tsv sims/svgs/train/qq_stats_m_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_130.tsv sims/svgs/train/roc_stats_m_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_140.tsv sims/svgs/train/qq_stats_m_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_140.tsv sims/svgs/train/roc_stats_m_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_150.tsv sims/svgs/train/qq_stats_m_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_150.tsv sims/svgs/train/roc_stats_m_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_160.tsv sims/svgs/train/qq_stats_m_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_160.tsv sims/svgs/train/roc_stats_m_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_170.tsv sims/svgs/train/qq_stats_m_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_170.tsv sims/svgs/train/roc_stats_m_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_180.tsv sims/svgs/train/qq_stats_m_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_180.tsv sims/svgs/train/roc_stats_m_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_190.tsv sims/svgs/train/qq_stats_m_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_190.tsv sims/svgs/train/roc_stats_m_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_200.tsv sims/svgs/train/qq_stats_m_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_200.tsv sims/svgs/train/roc_stats_m_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_210.tsv sims/svgs/train/qq_stats_m_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_210.tsv sims/svgs/train/roc_stats_m_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_220.tsv sims/svgs/train/qq_stats_m_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_220.tsv sims/svgs/train/roc_stats_m_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_230.tsv sims/svgs/train/qq_stats_m_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_230.tsv sims/svgs/train/roc_stats_m_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_240.tsv sims/svgs/train/qq_stats_m_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_240.tsv sims/svgs/train/roc_stats_m_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_250.tsv sims/svgs/train/qq_stats_m_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_250.tsv sims/svgs/train/roc_stats_m_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_70.tsv sims/svgs/train/qq_stats_m_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_70.tsv sims/svgs/train/roc_stats_m_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_80.tsv sims/svgs/train/qq_stats_m_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_80.tsv sims/svgs/train/roc_stats_m_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_m_90.tsv sims/svgs/train/qq_stats_m_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_m_90.tsv sims/svgs/train/roc_stats_m_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_100.tsv sims/svgs/train/qq_stats_ms_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_100.tsv sims/svgs/train/roc_stats_ms_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_110.tsv sims/svgs/train/qq_stats_ms_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_110.tsv sims/svgs/train/roc_stats_ms_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_120.tsv sims/svgs/train/qq_stats_ms_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_120.tsv sims/svgs/train/roc_stats_ms_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_130.tsv sims/svgs/train/qq_stats_ms_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_130.tsv sims/svgs/train/roc_stats_ms_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_140.tsv sims/svgs/train/qq_stats_ms_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_140.tsv sims/svgs/train/roc_stats_ms_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_150.tsv sims/svgs/train/qq_stats_ms_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_150.tsv sims/svgs/train/roc_stats_ms_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_160.tsv sims/svgs/train/qq_stats_ms_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_160.tsv sims/svgs/train/roc_stats_ms_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_170.tsv sims/svgs/train/qq_stats_ms_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_170.tsv sims/svgs/train/roc_stats_ms_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_180.tsv sims/svgs/train/qq_stats_ms_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_180.tsv sims/svgs/train/roc_stats_ms_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_190.tsv sims/svgs/train/qq_stats_ms_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_190.tsv sims/svgs/train/roc_stats_ms_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_200.tsv sims/svgs/train/qq_stats_ms_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_200.tsv sims/svgs/train/roc_stats_ms_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_210.tsv sims/svgs/train/qq_stats_ms_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_210.tsv sims/svgs/train/roc_stats_ms_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_220.tsv sims/svgs/train/qq_stats_ms_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_220.tsv sims/svgs/train/roc_stats_ms_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_230.tsv sims/svgs/train/qq_stats_ms_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_230.tsv sims/svgs/train/roc_stats_ms_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_240.tsv sims/svgs/train/qq_stats_ms_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_240.tsv sims/svgs/train/roc_stats_ms_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_250.tsv sims/svgs/train/qq_stats_ms_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_250.tsv sims/svgs/train/roc_stats_ms_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_70.tsv sims/svgs/train/qq_stats_ms_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_70.tsv sims/svgs/train/roc_stats_ms_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_80.tsv sims/svgs/train/qq_stats_ms_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_80.tsv sims/svgs/train/roc_stats_ms_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_ms_90.tsv sims/svgs/train/qq_stats_ms_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_ms_90.tsv sims/svgs/train/roc_stats_ms_90.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_100.tsv sims/svgs/train/qq_stats_r_100.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_100.tsv sims/svgs/train/roc_stats_r_100.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_110.tsv sims/svgs/train/qq_stats_r_110.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_110.tsv sims/svgs/train/roc_stats_r_110.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_120.tsv sims/svgs/train/qq_stats_r_120.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_120.tsv sims/svgs/train/roc_stats_r_120.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_130.tsv sims/svgs/train/qq_stats_r_130.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_130.tsv sims/svgs/train/roc_stats_r_130.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_140.tsv sims/svgs/train/qq_stats_r_140.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_140.tsv sims/svgs/train/roc_stats_r_140.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_150.tsv sims/svgs/train/qq_stats_r_150.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_150.tsv sims/svgs/train/roc_stats_r_150.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_160.tsv sims/svgs/train/qq_stats_r_160.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_160.tsv sims/svgs/train/roc_stats_r_160.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_170.tsv sims/svgs/train/qq_stats_r_170.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_170.tsv sims/svgs/train/roc_stats_r_170.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_180.tsv sims/svgs/train/qq_stats_r_180.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_180.tsv sims/svgs/train/roc_stats_r_180.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_190.tsv sims/svgs/train/qq_stats_r_190.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_190.tsv sims/svgs/train/roc_stats_r_190.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_200.tsv sims/svgs/train/qq_stats_r_200.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_200.tsv sims/svgs/train/roc_stats_r_200.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_210.tsv sims/svgs/train/qq_stats_r_210.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_210.tsv sims/svgs/train/roc_stats_r_210.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_220.tsv sims/svgs/train/qq_stats_r_220.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_220.tsv sims/svgs/train/roc_stats_r_220.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_230.tsv sims/svgs/train/qq_stats_r_230.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_230.tsv sims/svgs/train/roc_stats_r_230.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_240.tsv sims/svgs/train/qq_stats_r_240.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_240.tsv sims/svgs/train/roc_stats_r_240.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_250.tsv sims/svgs/train/qq_stats_r_250.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_250.tsv sims/svgs/train/roc_stats_r_250.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_70.tsv sims/svgs/train/qq_stats_r_70.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_70.tsv sims/svgs/train/roc_stats_r_70.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_80.tsv sims/svgs/train/qq_stats_r_80.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_80.tsv sims/svgs/train/roc_stats_r_80.svg
Rscript ~/vg/scripts/plot-qq.R sims/stats/train/stats_r_90.tsv sims/svgs/train/qq_stats_r_90.svg
Rscript ~/vg/scripts/plot-roc.R sims/stats/train/stats_r_90.tsv sims/svgs/train/roc_stats_r_90.svg
